name: Run CD
on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+' # e.g: v1.0.0
jobs:
  run-cd:
    runs-on: ubuntu-latest

    permissions:
      repository-projects: write
      contents: write
      id-token: write
      issues: write
      pull-requests: write

    env:
      APP_NAME: gosak

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 400

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: CI - format
        run: |
          make -f common.mk fmt
          if [ $? != 0 ]; then
            echo "FAIL"
            exit
          fi
      - name: CI - test
        run: |
          echo "TODO: test"

      - name: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/*/}"
        id: version

      - name: CD - build binary
        run: |
          echo "$(date)"
          make -f build.mk clean
          echo "Build binaries"
          make -f build.mk build-all

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifacts linux x86
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gosak.linux.amd64
          asset_name: gosak.linux.amd64
          asset_content_type: application/octet-stream
      - name: upload artifacts linux arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gosak.linux.arm64
          asset_name: gosak.linux.arm64
          asset_content_type: application/octet-stream
          
      - name: upload artifacts darwin x86
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gosak.darwin.amd64
          asset_name: gosak.darwin.amd64
          asset_content_type: application/octet-stream
      - name: upload artifacts darwin arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gosak.darwin.arm64
          asset_name: gosak.darwin.arm64
          asset_content_type: application/octet-stream